# DEPLOYMENT OF WEB-PAGE
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydeployment
      version: v01
  template:
    metadata:
      labels:
        app: mydeployment
        version: v01
    spec:
      containers:
        - name: web
          image: fabricioveronez/web-color:blue
          ports:
          - containerPort: 80
---
# SERVICE DO WEB-PAGE
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: mydeployment
  ports:
  - protocol: TCP
    port: 80
    name: http
    nodePort: 30000
  type: NodePort

