kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-page
spec:
  replicas: 3
  selector:
    #BBBBB
    matchLabels:
      app: mydeployment
      version: v01
  template:
    metadata:
      labels:
        app: mydeployment
        version: v01
    spec:
      containers:
        - name: web
          image: fabricioveronez/web-color:blue
          ports:
          - containerPort: 80
