kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-page
spec:
  #replicas: 4
  #AAAA
  selector:
    #BBBBB
    matchLabes:
      app: mydeployment
      version: v01
  template:
    metadata:
      labels:
        app: mydeployment
        version: v01
    spec:
      containers:
        - name: web
          image: francielrezende/web-page:blue
          ports:
          - containerPort: 80
