apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
spec:
  selector:
    matchLabes:
      app: mydeployment
  template:
    metadata:
      lables:
        app: mydeployment
    spec:
      containers:
        - name: web
          image: francielrezende/web-page:blue
          ports:
          - containerPort: 80
